Made changes to adjust for the MoveTypeTag. There an issue with const FVector_NetQuantize: 1>C:\Users\1351d\OneDrive\Documents\GitHub\ProjectPokemonMaster\ProjectMimikyu\Source\ProjectMimikyu\Private\Items\ProjectileAttack.cpp(189,55): error C2446: ':': no conversion from 'FVector' to 'const FVector_NetQuantize' 1>    ContactContext.ContactPoint = Hit.bBlockingHit ? Hit.ImpactPoint : OtherActor->GetActorLocation();